// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer_entity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CustomerModel _$CustomerModelFromJson(Map<String, dynamic> json) =>
    CustomerModel(
      Id: json['Id'] as int,
      CompanyId: json['CompanyId'] as int,
      Code: json['Code'] as String?,
      Name: json['Name'] as String?,
      IdentityId: json['IdentityId'] as num?,
      CountryId: json['CountryId'] as int?,
      CountryName: json['CountryName'] as String?,
      CountryNamear: json['CountryNamear'] as String?,
      CountryCode: json['CountryCode'] as String?,
      GovernateId: json['GovernateId'] as int?,
      GovernateName: json['GovernateName'] as String?,
      GovernateNamear: json['GovernateNamear'] as String?,
      City: json['City'] as String?,
      Street: json['Street'] as String?,
      BuilldingNumber: json['BuilldingNumber'] as String?,
      PostalCode: json['PostalCode'] as String?,
      Floor: json['Floor'] as String?,
      Room: json['Room'] as String?,
      Landmark: json['Landmark'] as String?,
      AdditionalInformation: json['AdditionalInformation'] as String?,
      Address: json['Address'] as String?,
      Address2: json['Address2'] as String?,
      TypeId: json['TypeId'] as int,
      TypeCode: json['TypeCode'] as String?,
      TypeName: json['TypeName'] as String?,
      Active: json['Active'] as bool,
      Mobile: json['Mobile'] as String?,
      Tel: json['Tel'] as String?,
      Fax: json['Fax'] as String?,
      Email: json['Email'] as String?,
      Website: json['Website'] as String?,
      CurrencyId: json['CurrencyId'] as int,
      CurrencyCode: json['CurrencyCode'] as String?,
      CurrencyName: json['CurrencyName'] as String?,
      CurrencyNamear: json['CurrencyNamear'] as String?,
      mobile: json['mobile'] as int,
      ItemCode: json['ItemCode'] as String?,
      ItemName: json['ItemName'] as String?,
      TaxTypeId: json['TaxTypeId'] as int,
      TaxTypeCode: json['TaxTypeCode'] as String?,
      TaxTypeName: json['TaxTypeName'] as String?,
      TaxTypeNamear: json['TaxTypeNamear'] as String?,
      TaxTypeSubId: json['TaxTypeSubId'] as int,
      TaxTypeSubCode: json['TaxTypeSubCode'] as String?,
      TaxTypeSubName: json['TaxTypeSubName'] as String?,
      TaxTypeSubNamear: json['TaxTypeSubNamear'] as String?,
      TaxRate: json['TaxRate'] as num,
      ContactPersons: (json['ContactPersons'] as List<dynamic>?)
          ?.map(
              (e) => CustomerContactPerson.fromJson(e as Map<String, dynamic>))
          .toList(),
      ShipAddresses: (json['ShipAddresses'] as List<dynamic>?)
          ?.map((e) => CustomerShipAddress.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$CustomerModelToJson(CustomerModel instance) =>
    <String, dynamic>{
      'id': instance.Id,
      'CompanyId': instance.CompanyId,
      'Code': instance.Code,
      'Name': instance.Name,
      'IdentityId': instance.IdentityId,
      'CountryId': instance.CountryId,
      'CountryName': instance.CountryName,
      'CountryNamear': instance.CountryNamear,
      'CountryCode': instance.CountryCode,
      'GovernateId': instance.GovernateId,
      'GovernateName': instance.GovernateName,
      'GovernateNamear': instance.GovernateNamear,
      'City': instance.City,
      'Street': instance.Street,
      'BuilldingNumber': instance.BuilldingNumber,
      'PostalCode': instance.PostalCode,
      'Floor': instance.Floor,
      'Room': instance.Room,
      'Landmark': instance.Landmark,
      'AdditionalInformation': instance.AdditionalInformation,
      'Address': instance.Address,
      'Address2': instance.Address2,
      'TypeId': instance.TypeId,
      'TypeCode': instance.TypeCode,
      'TypeName': instance.TypeName,
      'Active': instance.Active,
      'Mobile': instance.Mobile,
      'Tel': instance.Tel,
      'Fax': instance.Fax,
      'Email': instance.Email,
      'Website': instance.Website,
      'CurrencyId': instance.CurrencyId,
      'CurrencyCode': instance.CurrencyCode,
      'CurrencyName': instance.CurrencyName,
      'CurrencyNamear': instance.CurrencyNamear,
      'mobile': instance.mobile,
      'ItemCode': instance.ItemCode,
      'ItemName': instance.ItemName,
      'TaxTypeId': instance.TaxTypeId,
      'TaxTypeCode': instance.TaxTypeCode,
      'TaxTypeName': instance.TaxTypeName,
      'TaxTypeNamear': instance.TaxTypeNamear,
      'TaxTypeSubId': instance.TaxTypeSubId,
      'TaxTypeSubCode': instance.TaxTypeSubCode,
      'TaxTypeSubName': instance.TaxTypeSubName,
      'TaxTypeSubNamear': instance.TaxTypeSubNamear,
      'TaxRate': instance.TaxRate,
      'ContactPersons': instance.ContactPersons,
      'ShipAddresses': instance.ShipAddresses,
    };
