class IconAssets {
  static const splashIcon="assets/icons/splash_icon.png";
  static const englishIcon="assets/icons/english_icon.png";
  static const invoiceDisabledIcon="assets/icons/invoice_disabled_icon.png";
  static const invoiceActiveIcon="assets/icons/invoices_active_icon.png";
  static const productsActiveIcon="assets/icons/products_active_icon.png";
  static const productsDisabledIcon="assets/icons/products_disabled_icon.png";
  static const homeDisabledIcon="assets/icons/home_disabled_icon.png";
  static const homeActiveIcon="assets/icons/home_active_icon.png";
  static const moreDisabledIcon="assets/icons/more_disabled_icon.png";
  static const moreActiveIcon="assets/icons/more_disabled_icon.png";
  static const profileIcon="assets/icons/profile_icon.png";
  static const lockIcon="assets/icons/lock_icon.png";
  static const customersIcon="assets/icons/customer_icon.png";
  static const businessIcon="assets/icons/business_icon.png";
  static const addItemIcon="assets/icons/add_item_icon.png";
  static const addCustomerIcon="assets/icons/add_customer_icon.png";
  static const invoiceCustomerIcon="assets/icons/invoice_customer_icon.png";
  static const addDiscountIcon="assets/icons/add_discount_icon.png";
  static const logoutIcon="assets/icons/logout_icon.png";
}