class IconAssets {
  static const splashIcon="assets/icons/splash_icon.png";
  static const englishIcon="assets/icons/english_icon.png";
  static const invoiceDisabledIcon="assets/icons/disabled_invoice_icon.svg";
  static const invoiceActiveIcon="assets/icons/enabled_invoice_icon.svg";
  static const productsActiveIcon="assets/icons/enabled_products_icon.svg";
  static const productsDisabledIcon="assets/icons/disabled_products_icon.svg";
  static const homeDisabledIcon="assets/icons/disabled_home_icon.svg";
  static const homeActiveIcon="assets/icons/enabled_home_icon.svg";
  static const moreDisabledIcon="assets/icons/disabled_more_icon.svg";
  static const moreActiveIcon="assets/icons/enabled_more_icon.svg";
  static const profileIcon="assets/icons/profile_icon.png";
  static const lockIcon="assets/icons/lock_icon.png";
  static const customersIcon="assets/icons/customer_icon.png";
  static const businessIcon="assets/icons/business_icon.png";
  static const addItemIcon="assets/icons/add_item_icon.png";
  static const addCustomerIcon="assets/icons/add_customer_icon.png";
  static const invoiceCustomerIcon="assets/icons/invoice_customer_icon.png";
  static const addDiscountIcon="assets/icons/add_discount_icon.png";
  static const logoutIcon="assets/icons/logout_icon.png";
  static const handIcon="assets/icons/hand_icon.png";
  static const filterIcon="assets/icons/filter_icon.svg";
  static const languageIcon="assets/icons/language.png";
  static const subscribeIcon="assets/icons/subscribe_icon.png";
}